spring.application.name=loadtest

server.port=4200

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:65432/postgres
spring.datasource.username=postgres
spring.datasource.password=0987654321
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.show_sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.flyway.url=jdbc:postgresql://localhost:65432/postgres
spring.flyway.password=0987654321
spring.flyway.user=postgres


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.springframework.security.access.intercept=TRACE
logging.level.org.springframework.security.authentication=TRACE