services:
  postgres:
    image: postgres:18.4
    container_name: loadtest-postgres
    restart: always
    ports:
      - "18432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0987654321"
      POSTGRES_DB: postgres
    volumes:
      - /home/petr/data/pg/postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: loadtest-api
    restart: always
    ports:
      - "4200:4200"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "0987654321"
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: "0987654321"
    depends_on:
      postgres:
        condition: service_healthy

  node-exporter:
    image: prom/node-exporter:v1.9.0
    container_name: loadtest-node-exporter
    restart: always
    ports:
      - "9100:9100"

  k6:
    build:
      context: .
      dockerfile: Dockerfile.k6
    container_name: loadtest-k6
    user: "1000:1000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - .:/loadtest
    working_dir: /loadtest
    environment:
      NODE_EXPORTER_URL: http://node-exporter:9100
    ports:
      - "5665:5665"
    depends_on:
      - api
      - node-exporter

