services:
  postgres:
    image: postgres:18.4
    container_name: loadtest-postgres
    restart: always
    ports:
      - "18432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0987654321"
      POSTGRES_DB: postgres
    volumes:
      - loadtest_pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  loadtest_pgdata:
